version: "3.1"
services:
   eurekaserver1:
     image: 192.168.31.107:5000/snow-eureka-server:dev
     ports:
     - '20000:19090'
     environment:
     - spring.profiles.active=peer1
   eurekaserver2:
     image: 192.168.31.107:5000/snow-eureka-server:dev
     ports:
     - '20001:19090'
     environment:
     - spring.profiles.active=peer2
   eurekaserver3:
     image: 192.168.31.107:5000/snow-eureka-server:dev
     ports:
     - '20002:19090'
     environment:
     - spring.profiles.active=peer3
     	